
import React, { useRef, useState } from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { StudentProfile, CareerSuggestion, StreamSuggestion, BigFiveCategory, MBTICategory, RIASECCategory, ValueCategory, SkillRecommendation, ChatMessage, ChatRole, AppPhase, MBTIPole, MBTIPole as MBTIPoleType } from '../types';
import { BIG_FIVE_DESCRIPTIONS, MBTI_DESCRIPTIONS, RIASEC_DESCRIPTIONS, VALUE_DESCRIPTIONS } from '../constants';
import Chatbot from './Chatbot'; 
import { Chat } from '@google/genai'; 
import Card from './shared/Card';

interface ResultsDisplayProps {
  profile: StudentProfile;
  profileNarrative: string | null; 
  careerSuggestions: CareerSuggestion[];
  streamSuggestions: StreamSuggestion[];
  skillRecommendations?: SkillRecommendation[]; 
  onRetake: () => void;
  onBackToDashboard?: () => void;
  generalError?: string | null;
  chatSession: Chat | null;
  chatMessages: ChatMessage[];
  onSendChatMessage: (chat: Chat, messageText: string) => AsyncIterable<string>;
  addChatMessage: (message: ChatMessage) => void;
  updateLastBotMessage: (chunk: string, isLastChunk: boolean) => void;
  setChatError: (messageId: string, errorText: string) => void;
  navigateTo?: (phase: AppPhase, params?: any) => void;
}

const getScoreLevel = (score?: number): 'high' | 'moderate' | 'low' => {
  if (score === undefined) return 'moderate'; 
  if (score >= 3.8) return 'high';
  if (score >= 2.3) return 'moderate';
  return 'low';
};

const ScoreBar: React.FC<{ label: string; score: number; colorClass: string; interpretation: string }> = ({ label, score, colorClass, interpretation }) => {
  const percentage = (score / 5) * 100;
  const level = getScoreLevel(score);
  
  return (
    <div className="mb-6 animate-fade-in">
      <div className="flex justify-between items-end mb-2">
        <div>
          <span className="text-sm font-bold text-text-main">{label}</span>
          <span className={`ml-2 text-[10px] font-black uppercase px-2 py-0.5 rounded-full ${
            level === 'high' ? 'bg-green-100 text-green-700' : 
            level === 'moderate' ? 'bg-blue-100 text-blue-700' : 'bg-slate-100 text-slate-500'
          }`}>
            {level}
          </span>
        </div>
        <span className="text-xs font-mono font-bold text-text-muted">{score.toFixed(1)} / 5.0</span>
      </div>
      <div className="h-2 w-full bg-slate-100 rounded-full overflow-hidden">
        <div 
          className={`h-full transition-all duration-1000 ease-out ${colorClass}`} 
          style={{ width: `${percentage}%` }}
        />
      </div>
      <p className="text-[11px] text-text-muted mt-2 leading-relaxed italic">{interpretation}</p>
    </div>
  );
};

const ResultsDisplay: React.FC<ResultsDisplayProps> = ({ 
  profile, profileNarrative, careerSuggestions, streamSuggestions, skillRecommendations, onRetake, onBackToDashboard, generalError,
  chatSession, chatMessages, onSendChatMessage, addChatMessage, updateLastBotMessage, setChatError, navigateTo
}) => {
  const resultsContentRef = useRef<HTMLDivElement>(null);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const [showChatbot, setShowChatbot] = useState(false);

  const handleDownloadPdf = async () => {
    if (!resultsContentRef.current) return;
    setIsGeneratingPdf(true);
    try {
      const canvas = await html2canvas(resultsContentRef.current, { scale: 2 });
      const pdf = new jsPDF('p', 'mm', 'a4');
      const imgWidth = 210;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, 0, imgWidth, imgHeight);
      pdf.save('NextStep_CareerReport.pdf');
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  return (
    <div className="w-full max-w-6xl mx-auto pb-24 animate-fade-in">
      <div className="mb-10 flex flex-col sm:flex-row justify-between items-center bg-white p-6 rounded-3xl border border-slate-200 shadow-sm">
        <div>
          <h2 className="text-3xl font-bold font-serif text-text-main">Your Career Insight Report</h2>
          <p className="text-text-muted">Generated by Gemini Advanced Analytics</p>
        </div>
        <div className="flex gap-2 mt-4 sm:mt-0">
          <button onClick={handleDownloadPdf} disabled={isGeneratingPdf} className="px-6 py-3 bg-primary text-white font-bold rounded-xl shadow-lg hover:shadow-primary/30 transition-all active:scale-95 disabled:opacity-50">
            {isGeneratingPdf ? 'Processing...' : 'Export PDF'}
          </button>
          <button onClick={onBackToDashboard} className="px-6 py-3 bg-slate-100 text-text-muted font-bold rounded-xl hover:bg-slate-200 transition-all">
            Exit
          </button>
        </div>
      </div>

      <div ref={resultsContentRef} className="space-y-12 bg-white p-6 sm:p-12 rounded-[2rem] shadow-2xl border border-slate-100">
        {/* Profile Narrative Section */}
        {profileNarrative && (
          <section className="bg-gradient-to-br from-blue-50 to-white p-8 rounded-3xl border border-blue-100 shadow-sm">
            <h3 className="text-2xl font-bold text-primary mb-6 font-serif flex items-center">
               <svg className="w-7 h-7 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"></path></svg>
               Executive Profile Summary
            </h3>
            <div className="text-text-main text-lg leading-relaxed space-y-4">
              {profileNarrative}
            </div>
          </section>
        )}

        {/* NEW: Psychometric Scores Section */}
        <section className="space-y-10">
          <div className="flex items-center mb-4">
            <div className="h-10 w-2 bg-primary rounded-full mr-4"></div>
            <h3 className="text-2xl font-bold text-text-main">Psychometric Deep Dive</h3>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
            {/* Big Five Breakdown */}
            <div className="bg-slate-50/50 p-8 rounded-3xl border border-slate-100">
              <h4 className="text-lg font-bold text-primary mb-6 flex items-center">
                <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" strokeWidth="2"></path></svg>
                Personality Profile (Big Five)
              </h4>
              {Object.entries(profile.bigFive).map(([category, score]) => (
                <ScoreBar 
                  key={category}
                  label={category}
                  score={(score as number) || 0}
                  colorClass="bg-primary"
                  interpretation={BIG_FIVE_DESCRIPTIONS[category as BigFiveCategory][getScoreLevel(score as number)]}
                />
              ))}
            </div>

            {/* RIASEC Interests Breakdown */}
            <div className="bg-slate-50/50 p-8 rounded-3xl border border-slate-100">
              <h4 className="text-lg font-bold text-accent mb-6 flex items-center">
                <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" strokeWidth="2"></path></svg>
                Interest Inventory (Holland Codes)
              </h4>
              {Object.entries(profile.riasec).map(([category, score]) => (
                <ScoreBar 
                  key={category}
                  label={category}
                  score={(score as number) || 0}
                  colorClass="bg-accent"
                  interpretation={RIASEC_DESCRIPTIONS[category as RIASECCategory][getScoreLevel(score as number)]}
                />
              ))}
            </div>

            {/* Values Breakdown */}
            <div className="bg-slate-50/50 p-8 rounded-3xl border border-slate-100">
              <h4 className="text-lg font-bold text-amber-600 mb-6 flex items-center">
                <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" strokeWidth="2"></path></svg>
                Work Value Preferences
              </h4>
              {Object.entries(profile.values).map(([category, score]) => (
                <ScoreBar 
                  key={category}
                  label={category}
                  score={(score as number) || 0}
                  colorClass="bg-amber-500"
                  interpretation={VALUE_DESCRIPTIONS[category as ValueCategory][getScoreLevel(score as number)]}
                />
              ))}
            </div>

            {/* MBTI Dimensions Breakdown */}
            <div className="bg-slate-50/50 p-8 rounded-3xl border border-slate-100">
              <h4 className="text-lg font-bold text-indigo-600 mb-6 flex items-center">
                <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z" strokeWidth="2"></path></svg>
                Cognitive Style (MBTI Dimensions)
              </h4>
              <div className="space-y-8">
                {Object.entries(profile.mbti).map(([category, data]) => {
                  if (!data) return null;
                  const cat = category as MBTICategory;
                  const desc = MBTI_DESCRIPTIONS[cat];
                  const mbtiData = data as { dominantPole: MBTIPoleType; scoreDominant: number; scoreRecessive: number };
                  const domPole = mbtiData.dominantPole;
                  const isPole1 = desc.pole1.pole === domPole;
                  const dominantName = isPole1 ? desc.pole1.name : desc.pole2.name;
                  const dominantDesc = isPole1 ? desc.pole1.description : desc.pole2.description;

                  return (
                    <div key={category} className="p-4 bg-white rounded-2xl shadow-sm border border-indigo-50">
                      <div className="flex justify-between items-center mb-3">
                        <span className="text-xs font-black text-indigo-400 uppercase tracking-widest">{desc.dimension}</span>
                        <span className="text-sm font-bold text-indigo-700">{dominantName}</span>
                      </div>
                      <p className="text-xs text-text-muted leading-relaxed">{dominantDesc}</p>
                      <div className="mt-4 flex gap-1">
                         <div className={`h-1.5 flex-1 rounded-full ${isPole1 ? 'bg-indigo-600' : 'bg-slate-200'}`}></div>
                         <div className={`h-1.5 flex-1 rounded-full ${!isPole1 ? 'bg-indigo-600' : 'bg-slate-200'}`}></div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </section>

        {/* Career Suggestions Grid */}
        <section>
          <div className="flex items-center mb-8">
            <div className="h-10 w-2 bg-accent rounded-full mr-4"></div>
            <h3 className="text-2xl font-bold text-text-main">Top Career Matches</h3>
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {careerSuggestions.map((career, index) => (
              <Card key={index} className="flex flex-col border border-slate-100 hover:border-accent hover:shadow-xl transition-all h-full p-0 overflow-hidden">
                <div className="h-48 overflow-hidden bg-slate-100">
                  {career.dayInTheLifeImageUrl ? (
                    <img src={career.dayInTheLifeImageUrl} alt={career.name} className="w-full h-full object-cover" />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center text-slate-300">
                      <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"></path></svg>
                    </div>
                  )}
                </div>
                <div className="p-6 flex-grow">
                  <div className="flex justify-between items-start mb-2">
                    <h4 className="text-xl font-bold text-text-main leading-tight">{career.name}</h4>
                    {career.iscoCode && (
                       <span className="text-[10px] font-black bg-blue-100 text-blue-700 px-2 py-0.5 rounded uppercase">ISCO-{career.iscoCode}</span>
                    )}
                  </div>
                  <p className="text-sm text-text-muted line-clamp-2">{career.description}</p>
                  
                  <div className="mt-6 space-y-4">
                     <div className="p-3 bg-slate-50 rounded-xl">
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">Psychometric Match</p>
                        <p className="text-xs text-text-main leading-relaxed">{career.rationale}</p>
                     </div>
                  </div>
                </div>
                <div className="p-4 bg-slate-50 border-t border-slate-100 mt-auto">
                   <button 
                     onClick={() => navigateTo?.(AppPhase.OccupationsExplorer, { selectedCode: career.iscoCode })}
                     className="w-full py-2 bg-white border border-slate-200 rounded-lg text-xs font-bold text-primary hover:bg-primary hover:text-white transition-all shadow-sm"
                   >
                     View Global Standards
                   </button>
                </div>
              </Card>
            ))}
          </div>
        </section>

        {/* Skill Gap Analysis Section */}
        {skillRecommendations && skillRecommendations.length > 0 && (
          <section className="bg-amber-50/50 p-8 rounded-3xl border border-amber-100">
            <h3 className="text-2xl font-bold text-amber-800 mb-8 flex items-center">
              <svg className="w-7 h-7 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M13 10V3L4 14h7v7l9-11h-7z" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"></path></svg>
              Growth Plan: Skills to Master
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {skillRecommendations.map((skill, idx) => (
                <div key={idx} className="bg-white p-5 rounded-2xl shadow-sm border border-amber-200">
                  <h4 className="font-bold text-lg text-amber-900">{skill.skillName}</h4>
                  <p className="text-sm text-amber-700 mt-1">{skill.description}</p>
                  <div className="mt-4 flex flex-col gap-2">
                    {skill.learningResources?.slice(0, 1).map((res, rIdx) => (
                      <a key={rIdx} href={res.url} target="_blank" rel="noopener noreferrer" className="text-xs font-bold text-primary hover:underline flex items-center">
                         Explore {res.title}
                         <svg className="w-3 h-3 ml-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" strokeWidth="2"></path></svg>
                      </a>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}
      </div>

      {/* Floating Chatbot FAB */}
      <div className="fixed bottom-8 right-8 z-50">
        <button 
          onClick={() => setShowChatbot(!showChatbot)}
          className={`w-16 h-16 rounded-full shadow-2xl flex items-center justify-center transition-all transform hover:scale-110 active:scale-90 ${showChatbot ? 'bg-secondary rotate-45' : 'bg-primary'}`}
        >
          {showChatbot ? (
            <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M6 18L18 6M6 6l12 12" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"></path></svg>
          ) : (
            <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"></path></svg>
          )}
        </button>
      </div>

      {showChatbot && chatSession && (
        <div className="fixed bottom-28 right-8 z-50 w-[90vw] sm:w-[450px] animate-fade-in">
           <Chatbot
                chatSession={chatSession}
                initialMessages={chatMessages}
                onSendMessage={(session, text) => {
                    const botMsgId = `model-${Date.now()}`;
                    addChatMessage({ id: `user-${Date.now()}`, role: ChatRole.User, text, timestamp: Date.now() });
                    addChatMessage({ id: botMsgId, role: ChatRole.Model, text: "...", timestamp: Date.now() });
                    
                    return (async function*() {
                      let fullText = "";
                      for await (const chunk of onSendChatMessage(session, text)) {
                        fullText += chunk;
                        updateLastBotMessage(fullText + "...", false);
                      }
                      updateLastBotMessage(fullText, true);
                    })();
                }}
            />
        </div>
      )}
    </div>
  );
};

export default ResultsDisplay;
